In [2]:
import numpy as np

In [5]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

Méthodes ndarray

In [7]:
A.sum()

27

In [8]:
A.sum(axis=0)

array([ 8,  7, 12])

In [9]:
A.sum(axis=1)

array([ 8, 19])

In [10]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

In [11]:
A.min()

0

In [12]:
A.min(axis=0)

array([3, 0, 3])

In [13]:
A.min(axis=1)

array([0, 3])