In [2]:
import numpy as np

In [5]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

Méthodes ndarray

In [7]:
A.sum()

27

In [8]:
A.sum(axis=0)

array([ 8,  7, 12])

In [9]:
A.sum(axis=1)

array([ 8, 19])

In [10]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

In [11]:
A.min()

0

In [12]:
A.min(axis=0)

array([3, 0, 3])

In [13]:
A.min(axis=1)

array([0, 3])

Exo
Standardisation matrice 

In [3]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [7]:
D = (A - A.mean(axis=0)) / A.std(axis=0)
A.std(axis=0)

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [9]:
A = np.array([0, 5, 4, 5])
A.shape

(4,)